### ISSUE TITLE
How to use DensPart?

### ISSUE THREAD

**Issue by Nimishdwarakanath** [theochem/denspart_horton2#1]
Dear Developers,
I intend to derive force-field for a MOF using QuickFF. I have used the CP2K program to obtain the Ab Initio Hessian and charge density (cube file). To partition charge density to charges on atoms using HORTON, I wanted to use horton-cpart.py as described in the [Doc Page](https://theochem.github.io/horton/2.0.0/user_postproc_aim.html) and soon learned that the program was deprecated. As per Prof. Toon Verstraelen's [indication](https://github.com/theochem/horton/pull/117), I think it would be apt to use DensPart program. However, I am unable to find any documentation on its usage. Any help in this regard will be appreciated. Thanks in advance
Nimish.

**Comment by tovrstra** [comment]
A robust code for the periodic case is currently under development, but it is not released yet. (Also this repo is probably no longer relevant.)

**Comment by Nimishdwarakanath** [comment]
Thanks..
